### ISSUE TITLE
Crash of the client when trying to move the slider with a piston.

### ISSUE THREAD

**Issue by SKProCH** [ZigTheHedge/slideemall#3]
**Describe the bug**
Crash of the client when trying to move the slider with a piston.

**To Reproduce**
Put the piston, connect the slime block to it, connect the slider to the slime block, put something into the slider, activate the piston.

**Version information**
Forge version: 14.23.5.2838
Mod version: 0.95

**Crashlog**
https://pastebin.com/MDTKRGrm

**Comment by ZigTheHedge** [comment]
Just in case - try with 0.97

**Comment by SKProCH** [comment]
Sorry for the long delay. Now, apparently, everything has already been fixed, since the slider can no longer be moved by the piston, like obsidian.
